import { OfficialSourceRegistryRecord } from '../src/types.ts';

export const INITIAL_OFFICIAL_REGISTRY: OfficialSourceRegistryRecord[] = [
  {
    authority_id: 'tgpsc',
    authority_name: 'Telangana Public Service Commission (TGPSC)',
    authority_type: 'State PSC',
    state: 'Telangana',
    official_domain: 'websitenew.tgpsc.gov.in',
    notification_path: '/',
    syllabus_path: '/SyllabusCMS',
    question_paper_path: '/QuestionPapersCMS',
    answer_key_path: '/',
    results_path: '/',
    gazette_domain: 'gazette.telangana.gov.in',
    other_official_domains: ['tgpsc.gov.in', 'tspsc.gov.in', 'websitel.tgpsc.gov.in'],
    verified_at: '2026-08-15T10:00:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'tslprb',
    authority_name: 'Telangana State Level Police Recruitment Board (TSLPRB / TGPRB)',
    authority_type: 'Police Recruitment Board',
    state: 'Telangana',
    official_domain: 'tslprb.in',
    notification_path: '/',
    syllabus_path: '/',
    question_paper_path: '/',
    answer_key_path: '/',
    results_path: '/',
    gazette_domain: 'gazette.telangana.gov.in',
    other_official_domains: ['tspolice.gov.in'],
    verified_at: '2026-08-15T10:00:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'appsc',
    authority_name: 'Andhra Pradesh Public Service Commission (APPSC)',
    authority_type: 'State PSC',
    state: 'Andhra Pradesh',
    official_domain: 'psc.ap.gov.in',
    notification_path: '/Notifications.aspx',
    syllabus_path: '/Syllabus.aspx',
    question_paper_path: '/PreviousPapers.aspx',
    answer_key_path: '/Keys.aspx',
    results_path: '/Results.aspx',
    gazette_domain: 'apegazette.cgg.gov.in',
    other_official_domains: ['appsc.gov.in'],
    verified_at: '2026-08-10T12:00:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'tnpsc',
    authority_name: 'Tamil Nadu Public Service Commission (TNPSC)',
    authority_type: 'State PSC',
    state: 'Tamil Nadu',
    official_domain: 'tnpsc.gov.in',
    notification_path: '/notifications.html',
    syllabus_path: '/syllabus.html',
    question_paper_path: '/previous-question-papers.html',
    answer_key_path: '/answer-keys.html',
    results_path: '/results.html',
    gazette_domain: 'stationeryprinting.tn.gov.in',
    other_official_domains: ['tnpscexams.in'],
    verified_at: '2026-08-12T09:30:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'kerala_psc',
    authority_name: 'Kerala Public Service Commission (Kerala PSC)',
    authority_type: 'State PSC',
    state: 'Kerala',
    official_domain: 'keralapsc.gov.in',
    notification_path: '/notifications',
    syllabus_path: '/syllabus',
    question_paper_path: '/question-papers',
    answer_key_path: '/answer-keys',
    results_path: '/results',
    gazette_domain: 'egazette.kerala.gov.in',
    other_official_domains: ['thulasi.psc.kerala.gov.in'],
    verified_at: '2026-08-14T11:20:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'assam_psc',
    authority_name: 'Assam Public Service Commission (APSC)',
    authority_type: 'State PSC',
    state: 'Assam',
    official_domain: 'apsc.nic.in',
    notification_path: '/notif.asp',
    syllabus_path: '/syllabus.asp',
    question_paper_path: '/questions.asp',
    answer_key_path: '/answers.asp',
    results_path: '/results.asp',
    gazette_domain: 'assamgazette.nic.in',
    other_official_domains: ['apscrecruitment.in'],
    verified_at: '2026-07-28T14:15:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'kpsc',
    authority_name: 'Karnataka Public Service Commission (KPSC)',
    authority_type: 'State PSC',
    state: 'Karnataka',
    official_domain: 'kpsc.kar.nic.in',
    notification_path: '/notification.html',
    syllabus_path: '/syllabus.html',
    question_paper_path: '/previousqp.html',
    answer_key_path: '/keyanswers.html',
    results_path: '/results.html',
    gazette_domain: 'gazette.kar.nic.in',
    other_official_domains: ['kpscrecruitment.in'],
    verified_at: '2026-08-01T08:45:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'mpsc',
    authority_name: 'Maharashtra Public Service Commission (MPSC)',
    authority_type: 'State PSC',
    state: 'Maharashtra',
    official_domain: 'mpsc.gov.in',
    notification_path: '/advertisements',
    syllabus_path: '/syllabus',
    question_paper_path: '/question-papers',
    answer_key_path: '/answer-keys',
    results_path: '/results',
    gazette_domain: 'egazette.mahaonline.gov.in',
    other_official_domains: ['mpsconline.gov.in'],
    verified_at: '2026-08-05T10:00:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'rpsc',
    authority_name: 'Rajasthan Public Service Commission (RPSC)',
    authority_type: 'State PSC',
    state: 'Rajasthan',
    official_domain: 'rpsc.rajasthan.gov.in',
    notification_path: '/news',
    syllabus_path: '/syllabus',
    question_paper_path: '/questionpapers',
    answer_key_path: '/answerkeys',
    results_path: '/results',
    gazette_domain: 'rajegazette.rajasthan.gov.in',
    other_official_domains: ['sso.rajasthan.gov.in'],
    verified_at: '2026-08-11T13:30:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'uppsc',
    authority_name: 'Uttar Pradesh Public Service Commission (UPPSC)',
    authority_type: 'State PSC',
    state: 'Uttar Pradesh',
    official_domain: 'uppsc.up.nic.in',
    notification_path: '/Notifications.aspx',
    syllabus_path: '/Syllabus.aspx',
    question_paper_path: '/PreviousPapers.aspx',
    answer_key_path: '/AnswerKey.aspx',
    results_path: '/Results.aspx',
    gazette_domain: 'egazette.up.nic.in',
    other_official_domains: ['uppsc.org.in'],
    verified_at: '2026-08-16T15:00:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'bpsc',
    authority_name: 'Bihar Public Service Commission (BPSC)',
    authority_type: 'State PSC',
    state: 'Bihar',
    official_domain: 'bpsc.bih.nic.in',
    notification_path: '/notices',
    syllabus_path: '/syllabus',
    question_paper_path: '/prev_papers',
    answer_key_path: '/keys',
    results_path: '/results',
    gazette_domain: 'egazette.bih.nic.in',
    other_official_domains: ['onlinebpsc.bihar.gov.in'],
    verified_at: '2026-08-08T09:10:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'opsc',
    authority_name: 'Odisha Public Service Commission (OPSC)',
    authority_type: 'State PSC',
    state: 'Odisha',
    official_domain: 'opsc.gov.in',
    notification_path: '/Public/WhatsNew.aspx',
    syllabus_path: '/Public/Syllabus.aspx',
    question_paper_path: '/Public/PreviousPapers.aspx',
    answer_key_path: '/Public/AnswerKeys.aspx',
    results_path: '/Public/Results.aspx',
    gazette_domain: 'odishagazette.odisha.gov.in',
    other_official_domains: ['opsconline.gov.in'],
    verified_at: '2026-07-30T16:20:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'wbpsc',
    authority_name: 'West Bengal Public Service Commission (WBPSC)',
    authority_type: 'State PSC',
    state: 'West Bengal',
    official_domain: 'psc.wb.gov.in',
    notification_path: '/advertisements',
    syllabus_path: '/scheme-and-syllabus',
    question_paper_path: '/previous-questions',
    answer_key_path: '/answer-keys',
    results_path: '/results',
    gazette_domain: 'egazette.wb.gov.in',
    other_official_domains: ['wbpsc.gov.in'],
    verified_at: '2026-08-04T12:00:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'ssc',
    authority_name: 'Staff Selection Commission (SSC)',
    authority_type: 'Central Commission',
    state: 'Central',
    official_domain: 'ssc.gov.in',
    notification_path: '/notice-board',
    syllabus_path: '/scheme-of-examination',
    question_paper_path: '/model-papers',
    answer_key_path: '/tentative-answer-keys',
    results_path: '/results',
    gazette_domain: 'egazette.gov.in',
    other_official_domains: ['ssc.nic.in', 'ssconline.nic.in'],
    verified_at: '2026-08-18T10:00:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'upsc',
    authority_name: 'Union Public Service Commission (UPSC)',
    authority_type: 'Central Commission',
    state: 'Central',
    official_domain: 'upsc.gov.in',
    notification_path: '/examinations/active-examinations',
    syllabus_path: '/examinations/revised-syllabus',
    question_paper_path: '/examinations/previous-question-papers',
    answer_key_path: '/examinations/answer-keys',
    results_path: '/examinations/written-results',
    gazette_domain: 'egazette.gov.in',
    other_official_domains: ['upsconline.nic.in'],
    verified_at: '2026-08-19T14:00:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'rrb',
    authority_name: 'Railway Recruitment Control Board (RRB / Indian Railways)',
    authority_type: 'Railway Recruitment Board',
    state: 'Central',
    official_domain: 'indianrailways.gov.in',
    notification_path: '/railwayboard/view_section.jsp?lang=0&id=0,4,1244',
    syllabus_path: '/railwayboard/view_section.jsp?lang=0&id=0,4,1244,1245',
    question_paper_path: '/railwayboard/view_section.jsp?lang=0&id=0,4,1244,1247',
    answer_key_path: '/railwayboard/view_section.jsp?lang=0&id=0,4,1244,1246',
    results_path: '/railwayboard/view_section.jsp?lang=0&id=0,4,1244,1248',
    gazette_domain: 'egazette.gov.in',
    other_official_domains: [
      'rrbcdg.gov.in',
      'rrbsecunderabad.gov.in',
      'rrbchennai.gov.in',
      'rrbmumbai.gov.in',
      'rrbbnc.gov.in',
      'rrbkolkata.gov.in'
    ],
    verified_at: '2026-08-17T11:45:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'police_recruitment',
    authority_name: 'Police Recruitment Boards (State & Central CPO)',
    authority_type: 'Police Recruitment Board',
    state: 'Multi-State / Central',
    official_domain: 'tslprb.in',
    notification_path: '/notifications',
    syllabus_path: '/syllabus',
    question_paper_path: '/previous-papers',
    answer_key_path: '/key-answers',
    results_path: '/results',
    gazette_domain: 'gazette.telangana.gov.in',
    other_official_domains: [
      'uppbpb.gov.in',
      'tnusrb.tn.gov.in',
      'mahapolice.gov.in',
      'crpf.gov.in',
      'bsf.gov.in'
    ],
    verified_at: '2026-08-10T16:00:00Z',
    status: 'ACTIVE'
  },
  {
    authority_id: 'teacher_recruitment',
    authority_name: 'Teacher Recruitment Boards & Eligibility Authorities',
    authority_type: 'Teacher Recruitment Board',
    state: 'Multi-State / Central',
    official_domain: 'ctet.nic.in',
    notification_path: '/information-bulletin',
    syllabus_path: '/syllabus-and-structure',
    question_paper_path: '/archive-question-paper',
    answer_key_path: '/provisional-answer-key',
    results_path: '/results',
    gazette_domain: 'egazette.gov.in',
    other_official_domains: [
      'trb.tn.gov.in',
      'dsc.telangana.gov.in',
      'cse.ap.gov.in',
      'updeled.gov.in',
      'wbbpe.org'
    ],
    verified_at: '2026-08-12T13:20:00Z',
    status: 'ACTIVE'
  }
];
