import { jurisdictionMatches,subjectsForExam,type SubjectId } from '../src/researchCoverage.ts';
import type { ExamRecord } from '../src/types.ts';
export interface SubjectPublisher {
  tier?:'SECONDARY'|'EDUCATIONAL';
  path_prefix?:string;
  jurisdiction?:'Andhra Pradesh'|'Telangana';
  id:string; name:string; url:string; subjects:SubjectId[];
  mode:'FEED'|'HTML_NEWS'|'ICC_NEWS'|'REFERENCE'|'UNAVAILABLE'; kind:'CURRENT'|'REFERENCE';
  refresh_hours:number; note:string; title_filter?:RegExp;
}
export const SUBJECT_PUBLISHERS:SubjectPublisher[]=[
  {id:'telangana-today',name:'Telangana Today',url:'https://telanganatoday.com/feed',subjects:['state','schemes','sports','science','economy','environment','history','awards','reports'],jurisdiction:'Telangana',mode:'FEED',kind:'CURRENT',tier:'SECONDARY',refresh_hours:12,note:'Regional reporting. Each claim needs independent corroboration and date review; copied reports are one source.'},
  {id:'tnie-telangana',name:'The New Indian Express: Telangana',url:'https://www.newindianexpress.com/states/telangana',path_prefix:'/states/telangana/',subjects:['state','schemes','economy','environment','history','awards','reports'],jurisdiction:'Telangana',mode:'HTML_NEWS',kind:'CURRENT',tier:'SECONDARY',refresh_hours:12,note:'Telangana reporting; collect readable article text and corroborate claims before use.'},
  {id:'tnie-ap',name:'The New Indian Express: Andhra Pradesh',url:'https://www.newindianexpress.com/states/andhra-pradesh',path_prefix:'/states/andhra-pradesh/',subjects:['state','schemes','economy','environment','history','awards','reports'],jurisdiction:'Andhra Pradesh',mode:'HTML_NEWS',kind:'CURRENT',tier:'SECONDARY',refresh_hours:12,note:'Andhra Pradesh reporting; announcements must not be treated as completed implementation.'},
  {id:'openstax-biology',name:'OpenStax: the science of biology',url:'https://openstax.org/books/biology-2e/pages/1-1-the-science-of-biology',subjects:['science'],mode:'REFERENCE',kind:'REFERENCE',tier:'EDUCATIONAL',refresh_hours:720,note:'One educational chapter, not the whole science syllabus. Retain attribution and review concept alignment.'},
  {id:'openstax-percent',name:'OpenStax: understanding percent',url:'https://openstax.org/books/prealgebra-2e/pages/6-1-understand-percent',subjects:['math'],mode:'REFERENCE',kind:'REFERENCE',tier:'EDUCATIONAL',refresh_hours:720,note:'Percent concepts and worked examples. Generated numerical answers are calculated separately.'},
  {id:'icc',name:'ICC cricket news',url:'https://www.icc-cricket.com/news',subjects:['sports'],mode:'ICC_NEWS',kind:'CURRENT',refresh_hours:12,note:'Cricket only. Results, records and rankings need event/category checks.'},
  {id:'fide',name:'FIDE chess news',url:'https://www.fide.com/feed/',subjects:['sports'],mode:'FEED',kind:'CURRENT',refresh_hours:12,note:'Chess only. A preview is not a completed tournament result.'},
  {id:'pmindia-schemes',name:'PM India scheme announcements',url:'https://www.pmindia.gov.in/en/feed/?s=scheme&post_type=news_updates',subjects:['schemes'],mode:'FEED',kind:'CURRENT',refresh_hours:12,title_filter:/scheme|yojana|welfare|beneficiar|cabinet|programme|program|project/i,note:'Announcements need comparison with department guidelines.'},
  {id:'pmkisan',name:'PM-KISAN scheme portal',url:'https://www.pmkisan.gov.in/',subjects:['schemes'],mode:'REFERENCE',kind:'REFERENCE',refresh_hours:168,note:'Reference description and exclusions; effective version must be verified.'},
  {id:'pib',name:'PIB releases',url:'https://www.pib.gov.in/RssMain.aspx?ModId=6&Lang=1&Regid=1&reg=1',subjects:['schemes','science','economy','environment','polity','international'],mode:'FEED',kind:'CURRENT',refresh_hours:6,note:'Only subjects supported by article terms are assigned.'},
  {id:'isro',name:'ISRO press releases',url:'https://www.isro.gov.in/Press.html',subjects:['science'],mode:'FEED',kind:'CURRENT',refresh_hours:24,note:'Space science coverage only.'},
  {id:'rbi',name:'RBI press releases',url:'https://www.rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=',subjects:['economy'],mode:'FEED',kind:'CURRENT',refresh_hours:12,note:'Routine operational notices receive lower priority.'},
  {id:'mea',name:'Ministry of External Affairs press releases',url:'https://www.mea.gov.in/press-releases.htm',subjects:['international'],mode:'FEED',kind:'CURRENT',refresh_hours:12,title_filter:/bilateral|multilateral|foreign|international|summit|visit|agreement|treaty|united nations|g20|brics|sco/i,note:'Official diplomatic releases; a release is evidence of an announcement, not proof that an agreement took effect.'},
  {id:'moefcc',name:'MoEFCC environment ministry',url:'https://moef.gov.in/',subjects:['environment'],mode:'REFERENCE',kind:'REFERENCE',refresh_hours:168,note:'Ministry reference page for environment, forests, biodiversity and climate policy. Current claims require dated releases.'},
  {id:'ndma',name:'National Disaster Management Authority',url:'https://ndma.gov.in/',subjects:['environment'],mode:'UNAVAILABLE',kind:'REFERENCE',refresh_hours:168,note:'Cloudflare edge requests currently receive HTTP 522 from this origin. Keep disaster evidence in review and use PIB disaster releases until a bounded NDMA endpoint is available.'},
  {id:'legislative-constitution',name:'Legislative Department: Constitution of India',url:'https://legislative.gov.in/constitution-of-india/',subjects:['polity'],mode:'UNAVAILABLE',kind:'REFERENCE',refresh_hours:168,note:'The public page is a client-rendered application and does not expose the Constitution text to this server-side extractor yet.'},
  {id:'asi',name:'Archaeological Survey of India',url:'https://asi.nic.in/',subjects:['history'],mode:'UNAVAILABLE',kind:'REFERENCE',refresh_hours:168,note:'The public site redirects to an oversized homepage; a bounded monument/article adapter is still required.'},
  {id:'culture-ministry',name:'Ministry of Culture',url:'https://culture.gov.in/',subjects:['history'],mode:'REFERENCE',kind:'REFERENCE',refresh_hours:168,note:'Official culture and heritage reference. Programme announcements are not historical proof.'},
  {id:'india-geography',name:'National Portal: physical geography',url:'https://www.india.gov.in/explore-india/facts-of-india/physical-background/physical-features',subjects:['geography'],mode:'REFERENCE',kind:'REFERENCE',refresh_hours:168,note:'Physical features reference; individual facts still require review.'},
  {id:'telangana-profile',name:'Telangana state profile',url:'https://www.telangana.gov.in/about/state-profile/',subjects:['state','history','geography'],jurisdiction:'Telangana',mode:'REFERENCE',kind:'REFERENCE',refresh_hours:168,note:'Formation and state profile. Census/statistical reference years must be checked.'},
  {id:'ap-district-profile',name:'AP: Vizianagaram district profile',url:'https://vizianagaram.ap.gov.in/about-district/',subjects:['state','history','geography'],jurisdiction:'Andhra Pradesh',mode:'REFERENCE',kind:'REFERENCE',refresh_hours:168,note:'One district only; historical boundaries and administrative claims need version checks.'},
  {id:'myscheme',name:'myScheme discovery',url:'https://www.myscheme.gov.in/',subjects:['schemes'],mode:'UNAVAILABLE',kind:'REFERENCE',refresh_hours:168,note:'Public page does not expose usable scheme records to this extractor. Department sources are used instead.'},
  {id:'ncert',name:'NCERT educational resources',url:'https://ncert.nic.in/ebooks.php',subjects:['history','geography','science','math','english'],mode:'UNAVAILABLE',kind:'REFERENCE',refresh_hours:168,note:'Chapter/edition extraction adapter still required; catalogue links do not count as textbook evidence.'},
  {id:'india-code',name:'India Code',url:'https://indiacode.gov.in/',subjects:['polity','specialist'],mode:'UNAVAILABLE',kind:'REFERENCE',refresh_hours:168,note:'Act, section and amendment version extraction still required.'},
];
export const getSubjectPublisher=(id:string)=>SUBJECT_PUBLISHERS.find(p=>p.id===id);
export const publisherApplies=(publisher:SubjectPublisher,exam:ExamRecord)=>jurisdictionMatches(exam,publisher.jurisdiction)&&publisher.subjects.some(s=>subjectsForExam(exam).includes(s));
