import { QuestionGrayscaleVisual } from './QuestionGrayscaleVisual.tsx';
import { DiagramExamples } from './DiagramExamples.tsx';
import React,{useEffect,useState} from 'react';
import type { BankQuestion, PaperJob } from '../freeEngine.ts';

const control='mt-1 block w-full rounded-lg border border-slate-300 bg-white p-2 text-sm';
const button='rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40';
export function FreeEngineDesk({examId,cutoff}:{examId:string;cutoff:string}) {
  const [data,setData]=useState<any>();const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);
  const [mode,setMode]=useState('SUBJECT_WISE');const [subject,setSubject]=useState('');const [topic,setTopic]=useState('');const [chapters,setChapters]=useState<string[]>([]);const [count,setCount]=useState(25);const [difficulty,setDifficulty]=useState('MEDIUM');const [blueprint,setBlueprint]=useState('');
  const [source,setSource]=useState('');const [second,setSecond]=useState('');const [excerpt,setExcerpt]=useState('');const [excerpt2,setExcerpt2]=useState('');const [claim,setClaim]=useState('');const [answer,setAnswer]=useState('');const [eventDate,setEventDate]=useState('');const [reviewer,setReviewer]=useState('');
  const [answers,setAnswers]=useState<Record<string,string>>({});const [notes,setNotes]=useState<Record<string,string>>({});
  const [concept,setConcept]=useState('');
  const [visualChecks,setVisualChecks]=useState<Record<string,boolean>>({});
  useEffect(()=>{setSubject('');setTopic('');setChapters([]);setSource('');setSecond('');setBlueprint('');setExcerpt('');setExcerpt2('');setClaim('');setAnswer('');setEventDate('');},[examId]);
  useEffect(()=>{
    if(!examId){setData(undefined);return;}
    const abort=new AbortController();setError('');setData(undefined);
    fetch(`/api/free-engine/overview?exam_id=${encodeURIComponent(examId)}&cutoff=${encodeURIComponent(cutoff)}`,{signal:abort.signal})
      .then(async r=>{const body=await r.json();if(!r.ok)throw Error(body.error||'Cloud question bank is unavailable.');return body;})
      .then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});
    return ()=>abort.abort();
  },[examId,cutoff,revision]);
  async function submit(path:string,body:any,message:string) {
    setBusy(true);setError('');setNotice('');
    try {
      const response=await fetch('/api/free-engine'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
      const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed.');
      setNotice(message);setRevision(n=>n+1);
    }catch(e:any){setError(e.message);}finally{setBusy(false);}
  }
  const selected=data?.evidence?.find((e:any)=>e.source_id===source);const corroborating=data?.evidence?.find((e:any)=>e.source_id===second);
  const topicOptions=(data?.topics||[]).map((t:string)=><option key={t} value={t}>{t}</option>);
  if(!examId)return null;
  return <div className="space-y-4 rounded-xl border border-indigo-200 bg-white p-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-bold">Question bank & paper builder</h3><p className="mt-1 text-sm text-slate-600">Review evidence, build questions in the cloud, then assemble full or subject papers.</p></div><button type="button" disabled={busy} onClick={()=>setRevision(n=>n+1)} className="text-sm font-semibold text-indigo-700 underline">Refresh bank</button></div>
    {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    {notice&&<p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-800">{notice}</p>}
    <DiagramExamples/>
    {data&&<>
      <div className="grid gap-3 sm:grid-cols-3">{[['Checked questions',data.ready_questions],['Questions to review',data.review_questions],['Daily AI reservation',`${data.budget.reserved} / ${data.budget.limit}`]].map(([label,value])=><div key={label} className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-600">{label}</p><p className="font-bold">{value}</p></div>)}</div>
      <p className="text-xs text-slate-600">Budget uses conservative estimates; resets {new Date(data.budget.reset_at).toLocaleString()}. Paid fallback is disabled. One pending question is processed per cloud tick. Latest {data.source_limit} source records are considered; missing coverage stays visible.</p>
      <div className="flex flex-wrap items-center gap-3 text-sm"><button type="button" className="font-semibold text-indigo-700 underline disabled:opacity-40" disabled={busy} onClick={()=>submit('/check-ai',{},'Cloud AI responded. No mock questions were generated.')}>Check cloud AI connection</button><span className="text-slate-500">{data.ai_health?`Last connected: ${new Date(data.ai_health.checked_at).toLocaleString()}`:'Connection not yet tested'}</span></div>
      {!data.readiness?.can_generate&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Paper generation is blocked: {data.readiness?.missing_requirements?.join('; ')||'Exam verification is incomplete.'}</p>}
      <div className="grid gap-3 md:grid-cols-3">
        <label className="text-sm">Paper type<select aria-label="Bank paper type" className={control} value={mode} onChange={e=>setMode(e.target.value)}><option value="SUBJECT_WISE">Subject paper</option><option value="TOPIC_WISE">Topic practice</option><option value="FULL_LENGTH">Full paper from locked blueprint</option></select></label>
        <label className="text-sm">Subject<select aria-label="Bank subject" className={control} value={subject} onChange={e=>setSubject(e.target.value)}><option value="">Choose subject</option>{data.subjects.map((s:string)=><option key={s}>{s}</option>)}</select></label>
        <label className="text-sm">Topic / first chapter<select aria-label="Bank topic" className={control} value={topic} onChange={e=>{setTopic(e.target.value);setChapters([e.target.value]);}}><option value="">Choose topic</option>{topicOptions}</select></label>
      </div>
      {mode==='SUBJECT_WISE'&&<details className="rounded-lg border p-3"><summary className="cursor-pointer text-sm">Select chapters ({chapters.length}); questions are distributed evenly</summary><div className="mt-2 max-h-48 space-y-1 overflow-auto">{data.topics.map((t:string)=><label key={t} className="flex gap-2 text-sm"><input type="checkbox" checked={chapters.includes(t)} onChange={e=>setChapters(xs=>e.target.checked?[...xs,t]:xs.filter(x=>x!==t))}/>{t}</label>)}</div></details>}
      {mode==='FULL_LENGTH'?<label className="block text-sm">Locked blueprint<select aria-label="Bank blueprint" className={control} value={blueprint} onChange={e=>setBlueprint(e.target.value)}><option value="">Choose a verified, locked blueprint</option>{data.blueprints.map((b:any)=><option key={b.blueprint_id} value={b.blueprint_id}>{b.blueprint_id} — {b.question_count} questions</option>)}</select></label>:<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Questions<input aria-label="Bank question count" type="number" min={1} max={200} value={count} onChange={e=>setCount(Number(e.target.value))} className={control}/></label><label className="text-sm">Difficulty<select aria-label="Bank difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value)} className={control}><option value="EASY">Easy</option><option value="MEDIUM">Medium</option><option value="HARD">Hard</option></select></label></div>}
      <button type="button" className={button} disabled={busy||!data.readiness?.can_generate||(mode==='FULL_LENGTH'?!blueprint:!subject||!topic)} onClick={()=>submit('/jobs',{exam_id:examId,cutoff,mode,subject,topic,topics:chapters,count,difficulty,blueprint_id:mode==='FULL_LENGTH'?blueprint:undefined},'Paper request queued. The cloud worker will fill evidence and question gaps in small steps.')}>Queue questions for this paper</button>
      <p className="text-xs text-slate-600">Practice defaults: one mark and one minute per question, no negative marking. These are practice settings. Full papers use their locked blueprint.</p>
      <details className="rounded-lg border p-4"><summary className="cursor-pointer font-semibold">Review a supporting fact ({data.facts.length} reviewed)</summary><div className="mt-3 space-y-3">
        <p className="text-sm text-slate-600">Check the actual source, its date and the claim. This records a fact review and does not mark the exam or paper verified.</p>
        <label className="block text-sm">Your name<input aria-label="Fact reviewer" value={reviewer} onChange={e=>setReviewer(e.target.value)} className={control}/></label>
        <label className="block text-sm">Source<select aria-label="Fact source" value={source} onChange={e=>{setSource(e.target.value);setExcerpt('');}} className={control}><option value="">Choose retrieved evidence</option>{data.evidence.map((e:any)=><option key={e.source_id} value={e.source_id}>{e.title}</option>)}</select></label>
        {selected&&<div className="rounded bg-slate-50 p-3 text-sm"><a href={selected.url} target="_blank" rel="noreferrer" className="text-indigo-700 underline">Read source</a><p>Published: {selected.publication_date||'Unknown'} · {selected.kind}</p><p className="mt-2 max-h-44 overflow-auto whitespace-pre-wrap">{selected.text}</p></div>}
        <label className="block text-sm">Exact supporting excerpt<textarea aria-label="Fact excerpt" value={excerpt} onChange={e=>setExcerpt(e.target.value)} maxLength={4000} className={control}/></label>
        <label className="block text-sm">Second independent source (required for regional reporting)<select aria-label="Corroborating source" value={second} onChange={e=>setSecond(e.target.value)} className={control}><option value="">None</option>{data.evidence.filter((e:any)=>e.source_id!==source).map((e:any)=><option key={e.source_id} value={e.source_id}>{e.title}</option>)}</select></label>
        {corroborating&&<><a href={corroborating.url} target="_blank" rel="noreferrer" className="text-sm text-indigo-700 underline">Read second source</a><label className="block text-sm">Second exact excerpt<textarea aria-label="Corroborating excerpt" value={excerpt2} onChange={e=>setExcerpt2(e.target.value)} maxLength={4000} className={control}/></label></>}
        <label className="block text-sm">Verified claim<input aria-label="Fact claim" value={claim} onChange={e=>setClaim(e.target.value)} maxLength={1500} className={control}/></label>
        <label className="block text-sm">Blueprint concept (copy the requested concept for a full paper)<input aria-label="Fact concept" value={concept} onChange={e=>setConcept(e.target.value)} maxLength={500} className={control}/></label>
        <label className="block text-sm">Answer supported verbatim by the excerpts<input aria-label="Fact answer" value={answer} onChange={e=>setAnswer(e.target.value)} maxLength={300} className={control}/></label>
        {selected?.kind==='CURRENT'&&<label className="block text-sm">Actual event date<input aria-label="Fact event date" type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)} max={cutoff} className={control}/></label>}
        <p className="text-sm">Topic: {topic||'Choose a topic above'}</p>
        <button type="button" disabled={busy||!source||!topic||!reviewer.trim()||!claim.trim()||!answer.trim()} className={button} onClick={()=>submit('/facts/review',{exam_id:examId,cutoff,topic,concept,claim,answer,reviewer,kind:selected?.kind,event_date:eventDate,source_ids:[source,...(second?[second]:[])],source_hashes:[selected.content_hash,...(second?[corroborating.content_hash]:[])],excerpts:[excerpt,...(second?[excerpt2]:[])]},'Fact review saved with its source snapshots.')}>Save checked fact</button>
      </div></details>
      <details className="rounded-lg border p-4"><summary className="cursor-pointer font-semibold">Review question candidates ({data.review_questions})</summary><div className="mt-3 space-y-4">{data.bank.filter((q:BankQuestion)=>q.status==='REVIEW_REQUIRED').map((q:BankQuestion)=><article key={q.id} className="rounded-lg border p-4"><p className="text-xs text-slate-500">{q.subject} · {q.topic} · {q.difficulty} · {q.template_id?'Calculated template':'Evidence-based AI draft'}</p><p className="mt-2 font-semibold">{q.question.question_text}</p><QuestionGrayscaleVisual visual={q.question.visual_specification}/>{q.question.visual_specification&&<label className="my-3 flex items-start gap-2 text-sm"><input type="checkbox" checked={visualChecks[q.id]||false} onChange={e=>setVisualChecks(x=>({...x,[q.id]:e.target.checked}))}/>I checked the figure against the question: labels, units, values, shading, and no answer revealed.</label>}<ol className="mt-2 space-y-1">{q.question.options.map((o,i)=><li key={i}>{String.fromCharCode(65+i)}. {o}</li>)}</ol><p className="mt-3 text-sm">Explanation: {q.question.explanation}</p><label className="mt-3 block text-sm">Your independent answer<select aria-label={`Review answer ${q.id}`} value={answers[q.id]||''} onChange={e=>setAnswers(x=>({...x,[q.id]:e.target.value}))} className={control}><option value="">Select after checking</option>{q.question.options.map((o,i)=><option key={i} value={String(i)}>{String.fromCharCode(65+i)}. {o}</option>)}</select></label><label className="mt-2 block text-sm">Review note<input aria-label={`Review note ${q.id}`} value={notes[q.id]||''} onChange={e=>setNotes(x=>({...x,[q.id]:e.target.value}))} className={control}/></label><label className="mt-2 block text-sm">Reviewer<input value={reviewer} onChange={e=>setReviewer(e.target.value)} className={control}/></label><div className="mt-3 flex gap-3"><button type="button" disabled={busy||!reviewer.trim()||answers[q.id]===undefined||answers[q.id]===''||(q.question.visual_specification&&!visualChecks[q.id])||(notes[q.id]||'').length<10} className={button} onClick={()=>submit('/questions/review',{id:q.id,action:'accept',visual_checked:visualChecks[q.id]===true,answer_index:Number(answers[q.id]),reviewer,notes:notes[q.id]},'Question checked and added to the bank.')}>Accept checked question</button><button type="button" disabled={busy||!reviewer.trim()||(notes[q.id]||'').length<10} className="text-sm text-red-700 underline disabled:opacity-40" onClick={()=>submit('/questions/review',{id:q.id,action:'reject',reviewer,notes:notes[q.id]},'Question rejected.')}>Reject</button></div></article>)}</div></details>
      <div className="space-y-3"><h4 className="font-semibold">Paper requests</h4>{data.jobs.length===0&&<p className="text-sm text-slate-500">No paper requests yet.</p>}{data.jobs.map((job:PaperJob)=><article key={job.id} className="rounded-lg border p-3"><div className="flex flex-wrap justify-between gap-2"><strong className="text-sm">{job.mode==='FULL_LENGTH'?'Full paper':job.subject} · {job.count} questions</strong><span className="text-xs">{job.state.replaceAll('_',' ')}</span></div><p className="mt-1 text-sm text-slate-600">{job.issues.join(' ')}</p>{job.next_run_at&&<p className="mt-1 text-xs">Next check: {new Date(job.next_run_at).toLocaleString()}</p>}<button type="button" className={button+' mt-3'} disabled={busy||!data.readiness?.can_generate||job.state!=='READY'} onClick={()=>submit('/assemble',{job_id:job.id},'Paper saved. Open Master Papers & Audit to inspect and export it.')}>Assemble checked paper</button></article>)}</div>
    </>}
  </div>;
}
